name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: check and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: build
        run: make build
      - name: test
        run: |
          rm act/container/docker_run_test.go
          go test -race -short -v -cover -coverprofile coverage.txt ./... && echo "\n==>\033[32m Ok\033[m\n" || exit 1

  conventional-commits:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: conventional commits
      uses: webiny/action-conventional-commits@v1.3.1
